### ISSUE TITLE
Arbitrary write

### ISSUE THREAD

**Issue by shargon** [effectai/effect-network-neo#6]
In this method

https://github.com/effectai/effect-network/blob/eb136b829df5bb20368c1457ee3250ef815fcecb/contracts/java/token-lock/src/ai/effect/token/TokenLock.java#L53

 it is possible to use the `lockHeight` as a valid NEO address, 

![image](https://user-images.githubusercontent.com/3167973/35404642-febd2372-0203-11e8-92ba-f5af3e991811.png)

with this "exploit" it is possible to make `approve` without an admin account. Using this possible values:

```
from= Valid address
To= Owner address
value= Tokens
lockHeight= My Address
```

https://github.com/effectai/effect-network/blob/eb136b829df5bb20368c1457ee3250ef815fcecb/contracts/java/token/src/ai/effect/token/EffectToken.java#L131

This attack is difficult to explain, but i think is mandatory to add prefix in all storage, like this:

```
"lock_"+Address+BlockNumber
"balance_"+Address
"approve_"+Address
```
With this prefix, would be impossible to jump from one storage to another.

**Comment by shargon** [comment]
What should be the logic of this method? 
https://github.com/effectai/effect-network/blob/eb136b829df5bb20368c1457ee3250ef815fcecb/contracts/java/token-lock/src/ai/effect/token/TokenLock.java#L75
At this moment, anyone can call it as there is none Witness check.

**Comment by jeisses** [comment]
I think I understand your concern with the first exploit.

However, as these are 2 separate contracts they will not share any storage and it's not possible for `lock` to overlap with `approve`. Is this correct, or would you still recommend to perfix the 3 types of storage keys?

About the `unlock` functionality; we designed it so that anybody is able to unlock tokens when they are past the lockHeight. The function will always transfer the tokens from the tokenLock to the respective owner (`to`). The benefit of having anybody call the function is that we can unlock tokens for our advisors/team members, so they don't have to remember to do it later. Does this make sense?

**Comment by shargon** [comment]
Yes, you are right, the storages are isloated, i was confused and im thinking that was the same contract when write this comment, sorry 😕 . Then is not vulnerable now, but thinking in a possible future, i preffer preffixes 😆
